import type { Metadata } from 'next'
import { Toaster } from 'react-hot-toast'
import './globals.css'

export const metadata: Metadata = {
   title: 'Pursuit of Card',
   description: 'Generated by create next app',
}

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode
}>) {
   return (
      <html lang="en">
         <body className="bg-squid-game bg-cover bg-center bg-no-repeat bg-blend-soft-light">
            {children}
            <Toaster />
         </body>
      </html>
   )
}
